-- Migration: Clean Test Data
-- Date: 2025-12-07
-- Purpose: Delete all test data before schema migration
-- Note: This is safe because we only have test data

-- Step 1: Disable FK checks
SET FOREIGN_KEY_CHECKS = 0;

-- Delete from dependent tables first (respect original FKs)
DELETE FROM POSTING_LIKES;
DELETE FROM POSTING_COMMENTS;
DELETE FROM POSTINGS;
DELETE FROM CONVERSATION_PARTICIPANTS;
DELETE FROM MESSAGES;
DELETE FROM CONVERSATIONS;
DELETE FROM USER_PREFERENCES;
DELETE FROM USER_NOTIFICATION_PREFERENCES;
DELETE FROM USER_PRIVACY_SETTINGS;

-- Delete core tables that will be recreated (use IF EXISTS pattern)
DELETE FROM PARENT_CONSENT_RECORDS WHERE 1=1;
DELETE FROM OTP_TOKENS WHERE 1=1;
DELETE FROM USER_INVITATIONS WHERE 1=1;
DELETE FROM FAMILY_MEMBERS WHERE 1=1;
DELETE FROM app_users WHERE 1=1;

-- Drop tables that may not exist (use IF EXISTS)
DROP TABLE IF EXISTS JWT_REFRESH_TOKENS;
DROP TABLE IF EXISTS FAMILY_ACCESS_LOG;
DROP TABLE IF EXISTS FAMILY_INVITATIONS;

-- Re-enable FK checks
SET FOREIGN_KEY_CHECKS = 1;

-- Verify all is clean
SELECT 'Test data cleanup complete' as status;
SELECT 'app_users' as table_name, COUNT(*) as row_count FROM app_users
UNION ALL SELECT 'FAMILY_MEMBERS', COUNT(*) FROM FAMILY_MEMBERS
UNION ALL SELECT 'USER_INVITATIONS', COUNT(*) FROM USER_INVITATIONS
UNION ALL SELECT 'POSTINGS', COUNT(*) FROM POSTINGS;
